<?php
/**
 * Bundled icon packs.
 *
 * Icons are addressed by a pack-agnostic semantic key (`home`, `cart`, ...)
 * defined in assets/icons/catalog.json. Each SVG pack lives in
 * assets/icons/packs/<pack>.json and is generated by tools/build-icons.mjs.
 * Two virtual "font packs" map keys to icon-font classes the Lenz theme
 * already loads on every page: "fontawesome" (Font Awesome 6 Free, handle
 * `lenz-font-awesome`) and "lenz" (the theme's own `lenz-icon-*` glyphs,
 * handle `lenz-icons`). They only work while Lenz is the active theme.
 *
 * @package LenzPlus
 */

namespace LenzPlus\Core;

defined( 'ABSPATH' ) || exit;

/**
 * Catalog, SVG lookup with fallbacks, icon-font classes and SVG sanitizing.
 */
final class Icon_Library {

	public const FONT_AWESOME = 'fontawesome';

	public const LENZ = 'lenz';

	/** Pack used when neither the requested pack nor its fallback has an icon. */
	private const LAST_RESORT_PACK = 'tabler';

	/**
	 * Font Awesome Free styles bundled with Lenz: regular (outline, a smaller
	 * set) and solid. Brand icons keep their own `fab` prefix.
	 */
	public const FA_WEIGHTS = array( 'far', 'fas' );

	/** @var array|null */
	private static $catalog = null;

	/** @var array<string, array> Decoded packs keyed by pack id. */
	private static $packs = array();

	/**
	 * Semantic icon list and pack metadata.
	 *
	 * @return array{icons: array<int, array{key:string,label:string,keywords:string,fa:string,lenz:string,lenzActive:string}>, packs: array<string, array>}
	 */
	public static function catalog(): array {
		if ( null === self::$catalog ) {
			$catalog = self::read_json( 'catalog.json' );

			$catalog['packs'][ self::LENZ ] = array(
				'label'     => __( 'Lenz icons', 'lenz-plus' ),
				'license'   => __( 'Loaded by the Lenz theme', 'lenz-plus' ),
				'hasFilled' => true,
				'fallback'  => 'lucide',
			);

			$catalog['packs'][ self::FONT_AWESOME ] = array(
				'label'     => 'Font Awesome',
				'license'   => __( 'Loaded by the Lenz theme', 'lenz-plus' ),
				'hasFilled' => true,
				'fallback'  => null,
			);

			self::$catalog = $catalog + array(
				'icons' => array(),
				'packs' => array(),
			);
		}

		return self::$catalog;
	}

	/**
	 * Whether a pack is drawn with an icon font instead of inline SVG.
	 *
	 * @param string $pack Pack id.
	 */
	public static function is_font_pack( string $pack ): bool {
		return self::FONT_AWESOME === $pack || self::LENZ === $pack;
	}

	/**
	 * Whether a pack can be shown on this site: font packs need Lenz, which
	 * loads their stylesheets.
	 *
	 * @param string $pack Pack id.
	 */
	public static function is_available( string $pack ): bool {
		return ! self::is_font_pack( $pack ) || Theme_Bridge::is_active();
	}

	/** @return string[] All selectable pack ids, including the font packs. */
	public static function pack_ids(): array {
		return array_keys( self::catalog()['packs'] );
	}

	/** @return string[] Every semantic icon key. */
	public static function icon_keys(): array {
		return wp_list_pluck( self::catalog()['icons'], 'key' );
	}

	/**
	 * Icons of an SVG pack: `{ key: { svg, active? } }`.
	 *
	 * @param string $pack Pack id.
	 */
	public static function pack( string $pack ): array {
		if ( ! isset( self::$packs[ $pack ] ) ) {
			$file                 = 'packs/' . sanitize_file_name( $pack ) . '.json';
			self::$packs[ $pack ] = self::read_json( $file );
		}

		return self::$packs[ $pack ];
	}

	/**
	 * Returns an inline SVG for a semantic key, walking the fallback chain
	 * (pack → its fallback → last-resort pack) when the key is missing.
	 *
	 * @param string $pack   SVG pack id.
	 * @param string $key    Semantic icon key.
	 * @param bool   $active Prefer the filled variant when the pack has one.
	 * @param string $class_name Class attribute added to the <svg>.
	 */
	public static function svg( string $pack, string $key, bool $active = false, string $class_name = '' ): string {
		$packs   = self::catalog()['packs'];
		$visited = array();

		while ( '' !== $pack && ! isset( $visited[ $pack ] ) ) {
			$visited[ $pack ] = true;
			$icon             = self::pack( $pack )[ $key ] ?? null;

			if ( $icon ) {
				$svg = ( $active && ! empty( $icon['active'] ) ) ? $icon['active'] : $icon['svg'];
				return self::decorate( $svg, $class_name );
			}

			$pack = (string) ( $packs[ $pack ]['fallback'] ?? self::LAST_RESORT_PACK );
		}

		return '';
	}

	/**
	 * Whether a pack ships a distinct filled icon for the key.
	 *
	 * @param string $pack SVG pack id.
	 * @param string $key  Semantic icon key.
	 */
	public static function has_active_variant( string $pack, string $key ): bool {
		if ( self::LENZ === $pack ) {
			return '' !== ( self::icon( $key )['lenzActive'] ?? '' );
		}

		return self::FONT_AWESOME === $pack || ! empty( self::pack( $pack )[ $key ]['active'] );
	}

	/**
	 * Font Awesome class list for a semantic key, e.g. `fal fa-home`.
	 * Brand icons keep their own `fab` prefix regardless of the weight.
	 *
	 * @param string $key    Semantic icon key.
	 * @param string $weight One of self::FA_WEIGHTS.
	 */
	public static function fa_class( string $key, string $weight ): string {
		$icon = self::icon( $key );
		if ( ! $icon ) {
			return $weight . ' fa-circle';
		}

		return 0 === strpos( $icon['fa'], 'fab ' ) ? $icon['fa'] : $weight . ' ' . $icon['fa'];
	}

	/**
	 * Lenz glyph class for a semantic key (`lenz-icon-cart`), or '' when the
	 * theme's font has no such glyph and an SVG fallback must be used. Lenz
	 * styles the glyph through `[class^=lenz-icon-]`, so the class must come
	 * first in the attribute or follow a space.
	 *
	 * @param string $key    Semantic icon key.
	 * @param bool   $active Prefer the bold/filled glyph when there is one.
	 */
	public static function lenz_class( string $key, bool $active = false ): string {
		$icon  = self::icon( $key );
		$glyph = (string) ( $active && ! empty( $icon['lenzActive'] ) ? $icon['lenzActive'] : ( $icon['lenz'] ?? '' ) );

		return '' === $glyph ? '' : 'lenz-icon-' . $glyph;
	}

	/**
	 * Catalog entry of one semantic key.
	 *
	 * @param string $key Semantic icon key.
	 * @return array<string, string>|null
	 */
	private static function icon( string $key ): ?array {
		foreach ( self::catalog()['icons'] as $icon ) {
			if ( $icon['key'] === $key ) {
				return $icon;
			}
		}

		return null;
	}

	/**
	 * Strips everything but presentational SVG markup from user supplied SVG.
	 *
	 * @param string $svg Raw SVG markup.
	 */
	public static function sanitize_svg( string $svg ): string {
		$svg = trim( $svg );
		if ( '' === $svg || false === stripos( $svg, '<svg' ) ) {
			return '';
		}

		// Drop XML prologs, doctypes and comments before kses sees them.
		$svg = preg_replace( '/<\?xml.*?\?>|<!DOCTYPE[^>]*>|<!--.*?-->/is', '', $svg );

		$common = array(
			'class'             => true,
			'fill'              => true,
			'fill-rule'         => true,
			'fill-opacity'      => true,
			'clip-rule'         => true,
			'clip-path'         => true,
			'stroke'            => true,
			'stroke-width'      => true,
			'stroke-linecap'    => true,
			'stroke-linejoin'   => true,
			'stroke-miterlimit' => true,
			'stroke-dasharray'  => true,
			'stroke-opacity'    => true,
			'opacity'           => true,
			'transform'         => true,
			'style'             => true,
			'id'                => true,
		);

		$shape = static function ( array $attrs ) use ( $common ): array {
			return array_fill_keys( $attrs, true ) + $common;
		};

		$allowed = array(
			'svg'            => $shape( array( 'viewbox', 'xmlns', 'width', 'height', 'preserveaspectratio', 'aria-hidden', 'role', 'focusable' ) ),
			'g'              => $common,
			'defs'           => array(),
			'title'          => array(),
			'path'           => $shape( array( 'd', 'pathlength' ) ),
			'circle'         => $shape( array( 'cx', 'cy', 'r' ) ),
			'ellipse'        => $shape( array( 'cx', 'cy', 'rx', 'ry' ) ),
			'rect'           => $shape( array( 'x', 'y', 'width', 'height', 'rx', 'ry' ) ),
			'line'           => $shape( array( 'x1', 'y1', 'x2', 'y2' ) ),
			'polyline'       => $shape( array( 'points' ) ),
			'polygon'        => $shape( array( 'points' ) ),
			'clippath'       => $shape( array( 'clippathunits' ) ),
			'lineargradient' => $shape( array( 'x1', 'y1', 'x2', 'y2', 'gradientunits', 'gradienttransform' ) ),
			'radialgradient' => $shape( array( 'cx', 'cy', 'r', 'fx', 'fy', 'gradientunits', 'gradienttransform' ) ),
			'stop'           => $shape( array( 'offset', 'stop-color', 'stop-opacity' ) ),
		);

		return trim( wp_kses( $svg, $allowed ) );
	}

	/**
	 * Adds accessibility attributes (and an optional class) to a trusted SVG.
	 *
	 * @param string $svg        Bundled SVG markup starting with `<svg`.
	 * @param string $class_name Class attribute value.
	 */
	public static function decorate( string $svg, string $class_name = '' ): string {
		$attrs = ' aria-hidden="true" focusable="false"';
		if ( '' !== $class_name ) {
			$attrs .= ' class="' . esc_attr( $class_name ) . '"';
		}

		return (string) preg_replace( '/^<svg\b/i', '<svg' . $attrs, $svg, 1 );
	}

	/**
	 * Decodes a JSON file shipped in assets/icons/ (empty array when missing).
	 *
	 * @param string $relative Path inside assets/icons/.
	 */
	private static function read_json( string $relative ): array {
		$path = LENZ_PLUS_DIR . 'assets/icons/' . $relative;
		if ( ! is_readable( $path ) ) {
			return array();
		}

		$data = json_decode( (string) file_get_contents( $path ), true ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents -- local file.

		return is_array( $data ) ? $data : array();
	}
}
